[Settings]
;start_path = "C:\Work\Documents"
start_path = /home/kirill/Downloads/Search-sys-test/
extensions = txt,md,ini,csv

[Database]
host = localhost
port = 5432
bd_name = postgres
username = postgres
password = ""